# Generated by Django 3.1.1 on 2020-10-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201005_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmacy',
            old_name='dysbioz_kyshechnyku',
            new_name='пваррапр',
        ),
    ]
