# Generated by Django 3.1.1 on 2020-10-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201008_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmacy',
            old_name='adult',
            new_name='В акушерсько-гінекологічній практиці при неспецифічних запальних захворюваннях геніталій та передпологовій підготовці вагітних групи ризику із порушенням чистоти вагінального секрету до III―IV ступеня',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='manufacturer',
            new_name='Виробник',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='children_age',
            new_name='Вік дитини',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='children',
            new_name='Гостра вірусна діарея',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='пваррапр',
            new_name='Гостра та хронічна бактеріальна діарея',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='name',
            new_name='Найменування',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='age_choice',
            new_name='Опреділення віку',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='temp_from',
            new_name='Температура зберігання від',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='temp_to',
            new_name='Температура зберігання до',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='expiration_date',
            new_name='Термін придатності',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='Vacation_conditions',
            new_name='Умови відпуску',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='form',
            new_name='Форма випуску',
        ),
        migrations.RenameField(
            model_name='farmacy',
            old_name='registration_form',
            new_name='Форма реєстрації',
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Гострі та хронічні шлунково-кишкові захворювання, пов’язані з інтоксикацією',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Дисбіоз кишечнику',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Для дорослих',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Для дітей',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Для профілактики патологічних колонізацій у кишечнику в новонароджених',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Для підвищення імунітету новонароджених',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Діарея мандрівника',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Діарея у дітей грудного та дошкільного віку, в тому числі при годуванні через зонд',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Діарея, пов’язана з довгостроковим ентеральним харчуванням',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Лікування транзиторних дисфункцій кишечнику (як діареї, так і запору), пов’язаних зі зміною харчового раціону',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Неспецифічний виразковий коліт у стадії ремісії',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Попередження та лікування діареї, спричиненої застосуванням антибіотиків або інших синтетичних протимікробних препаратів',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Порушеннями з боку кишечнику в осіб, які перенесли гострі кишкові інфекції, спричинені патогенними і умовно-патогенними бактеріями',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Профілактика та лікування гострих гастроентеритів у дітей та дорослих',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Профілактика та лікування колітів, пов’язаних з прийомом антибіотиків',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Псевдомембранозний коліт і захворювання, зумовлені Clostridium difficile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Підвищення толерантності до лактози молока',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Підтримуюча терапія при кропив’янці, екземі, дитячому діатезі, атопічному дерматиті',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Синдром  подразненого кишечника',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='У комплексному лікуванні захворювань шлунка і дванадцятипалої кишки, асоційованих із Helicobacter pylori',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Хронічні запори',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='Хронічні коліти різної етіології, у тому числі неспецифічні виразкові коліти',
            field=models.BooleanField(default=False),
        ),
    ]
