# Generated by Django 3.1.6 on 2021-02-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201214_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacy',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
