# Generated by Django 3.1.6 on 2021-02-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_farmacy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
