# Generated by Django 3.1.6 on 2021-02-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210202_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmacy',
            old_name='Найменування',
            new_name='Найменування ш',
        ),
    ]
