# Generated by Django 3.1.6 on 2021-02-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210202_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacy',
            name='Найменування ш',
        ),
        migrations.AddField(
            model_name='farmacy',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Найменування'),
        ),
    ]
