# Generated by Django 3.1.6 on 2021-02-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210202_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacy',
            name='temp_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Температура зберігання від'),
        ),
        migrations.AlterField(
            model_name='farmacy',
            name='temp_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Температура зберігання до'),
        ),
    ]
